version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123qq321
      POSTGRES_DB: TiburonTestDb
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  api:
    image: razrad3001/tiburontestapi
    container_name: api
    ports:
      - 8000:80
    environment:
      POSTGRES_HOST: db
    restart: always
    links: 
      - db
  client: 
    image: razrad3001/tiburontestfront
    container_name: client
    ports:
      - 3000:3000
    restart: always
volumes:
  pgdata:
    external: true